# WhatATheme
markdown: kramdown

# URL of the Site
url: https://sentientcoffee.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
# baseurl:

# Title of the Site
title: Daniel Presas
# Description of the Site
description: Programmer for tools, graphics, and networking
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: programmer, graphics, networking, engine, tools, systems
# URL for the Image of custom Favicon
favicon-url: /assets/images/despresso.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://p1.pxfuel.com/preview/793/318/452/source-code-code-programming-c.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: daniel.presas2000@gmail.com
github_username:    SentientCoffee
itchio_username:    SentientCoffee
linkedin_username:  daniel-presas
twitter_username:   sentientcoffee
youtube_channel_id: # UCk_93NXYP-U_AOB5GfWlOow
reddit_username:    # /
spotify_username:   # /
facebook_username:  # thedevslot
instagram_username: # thedevslot
behance_username:   # /
dribbble_username:  # /

# Google Analytics
# google-analytics: UA-163806439-1

# Disqus
# disqus-shortname: thedevslot

# Name of the Author
author-name: Daniel Presas
# URL for the Image of the Author
author-image: /assets/images/linkedin.jpg
# 60 Words About the Author
author-about: >
  Experienced game engine and software tools developer with experience in a multitude of languages,
  such as C, C++, C#, and Flutter + Dart.
author-about-long: >
  Hi, I'm Daniel Presas. I'm an experienced game engine and software tools developer, with interests in many
  different technologies and languages that can help me achieve my goals. I have worked with many different
  teams, as well as on my own, on a multitude of projects ranging from computer vision to audio to mobile applications,
  although my primary passion lies with game engines and the different technologies required to run them, such
  as graphics rendering, networking, and code architecture. Being involved in this space allows me to be able to help
  and advance the tools and technologies we use on a daily basis so that other people can work better, and reach their
  goals more effectively.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/SentientCoffee

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:slug"

# Compress
compress_html:
  clippings: all

# Collections
collections:
  projects:
    output: true
    permalink: ":collection/:slug"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project-page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .vscode/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
